package research.project.documate.backend.Backend.DTOs.Readme;

import lombok.Builder;
import lombok.Data;

import java.util.List;

@Data
@Builder
public class ReadmeGenerationResultDTO {
    private Long projectId;
    private String content;
    private String changeSummary;
    private List<String> keyFeatures;
    private List<String> setupSteps;
    private Boolean isAutoGenerated;
}
