package research.project.documate.backend.Backend.DTOs.GitIgnore;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class GitignoreGenerationResultDTO {
    private Long projectId;
    private String content;
    private String changeSummary;
    private Boolean isAutoGenerated;
}
