package research.project.documate.backend.Backend.Entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;

import java.time.LocalDateTime;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class ReadmeFileEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @OneToOne
    @JoinColumn(name = "project_id")
    private ProjectEntity project;

    @Lob // for large data
    private String content;

    private String commitHash; // each readme code (type of ID)
    private Boolean isAutoGenerated;
    private String changeSummary; // diff comparison

    @CreatedDate
    private LocalDateTime createdAt;
}
