package research.project.documate.backend.Backend.Service.Support;

import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import research.project.documate.backend.Backend.DTOs.Readme.GitDiffAnalysisDTO;
import research.project.documate.backend.Backend.DTOs.Readme.GitPushEventDTO;
import research.project.documate.backend.Backend.DTOs.Readme.ReadmeGenerationResultDTO;
import research.project.documate.backend.Backend.Entity.ProjectEntity;
import research.project.documate.backend.Backend.Entity.ReadmeFileEntity;
import research.project.documate.backend.Backend.Repository.ProjectRepository;
import research.project.documate.backend.Backend.Repository.ReadmeFileRepository;
import research.project.documate.backend.Backend.Service.AiService.ReadmeAiService;

import java.time.LocalDateTime;
import java.util.List;

@Service
@Slf4j
@AllArgsConstructor
public class GitTriggerService {
    private final ProjectRepository projectRepository;
    private final ReadmeFileRepository readmeFileRepository;
    private final GitDiffService gitDiffService;
    private final ReadmeAiService readmeAiService;

    public void processGitPush(GitPushEventDTO pushEvent) {
        try {
            log.info("STARTING Git push processing for project ID: {}", pushEvent.getProjectId());
            launchNotification("DocuMate System Started - Processing README update for project ID: " + pushEvent.getProjectId());
            log.info("Looking up project with ID: {}", pushEvent.getProjectId());
            ProjectEntity project = projectRepository.findById(pushEvent.getProjectId())
                    .orElseThrow(() -> {
                        log.error("Project not found with ID: {}. Available projects:", pushEvent.getProjectId());
                        projectRepository.findAll().forEach(p ->
                                log.info(" - ID: {}, Title: {}, Path: {}", p.getId(), p.getTitle(), p.getLocalPath()));
                        return new RuntimeException("Project not found with ID: " + pushEvent.getProjectId());
                    });

            log.info("Found project: {} (ID: {})", project.getTitle(), project.getId());
            log.info("Looking up current README for project ID: {}", project.getId());
            ReadmeFileEntity currentReadme = readmeFileRepository.findByProjectId(project.getId())
                    .orElseThrow(() -> {
                        log.error("No README found for project ID: {}", project.getId());
                        return new RuntimeException("No README found for project");
                    });
            log.info("Found current README ID: {}", currentReadme.getId());

            GitDiffAnalysisDTO diffAnalysis = gitDiffService.analyzeChanges(project, pushEvent.getCommitHash());

            String currentContent = currentReadme.getContent();
            ReadmeGenerationResultDTO newReadme = readmeAiService.generateUpdatedReadme(
                    project, currentContent, diffAnalysis);
            log.info("the newly generated readme content is as follows : {}" + newReadme.getContent());

            String pendingCommitHash = "PENDING_" + System.currentTimeMillis();

            ReadmeFileEntity updatedReadme = ReadmeFileEntity.builder() // Save new README with pending status
                    .project(project)
                    .content(newReadme.getContent())
                    .commitHash(pendingCommitHash)
                    .isAutoGenerated(true)
                    .changeSummary(newReadme.getChangeSummary())
                    .createdAt(LocalDateTime.now())
                    .build();

            log.info("Saving new README to database...");
            ReadmeFileEntity savedReadme = readmeFileRepository.save(updatedReadme);

            log.info("New README generated and saved with ID: {} for project: {}",
                    savedReadme.getId(), project.getTitle());

            // Verify it was saved by querying the database (debugging)
            List<ReadmeFileEntity> allReadmes = readmeFileRepository.findByProjectOrderByCreatedAtDesc(project);
            log.info("After save - Total READMEs in DB: {}", allReadmes.size());
            allReadmes.forEach(r ->
                    log.info("   - ID: {}, Commit: {}, Created: {}",
                            r.getId(), r.getCommitHash(), r.getCreatedAt())
            ); //Debugging

            launchNotification("README generated successfully! Project: " + project.getTitle());
            log.info("Git push processing completed successfully!");

        } catch (Exception e) {
            log.error("Error processing git push for project ID: {}", pushEvent.getProjectId(), e);
            launchNotification("Error processing README: " + e.getMessage());
            throw new RuntimeException("Error processing push", e);
        }
    }

    private void launchNotification(String message) {
        try {
            String command;
            if (System.getProperty("os.name").toLowerCase().contains("windows")) {
                command = "cmd.exe /c mshta vbscript:Execute(\"msgbox \"\"" + message + "\"\"\":close\")";
            } else {
                command = "zenity --info --text=\"" + message + "\"";
            }

            ProcessBuilder builder = new ProcessBuilder(command.split(" "));
            builder.start();

        } catch (Exception e) {
            log.error("Failed to show popup", e);
        }
    }
}
