package research.project.documate.backend.Backend.Service.AiService;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import research.project.documate.backend.Backend.DTOs.Docker.DockerGenerationResultDTO;
import research.project.documate.backend.Backend.DTOs.Project.ProjectAnalysisDTO;
import research.project.documate.backend.Backend.Entity.ProjectEntity;

@Service
@Slf4j
@AllArgsConstructor
public class DockerAiService {
    private final GeminiService geminiService;

    public DockerGenerationResultDTO generateDockerFile(ProjectEntity project, ProjectAnalysisDTO analysis, String currentContent) {
        String prompt = createDockerPrompt(project, analysis, currentContent);
        String aiResponse = geminiService.generateContent(prompt);
        return processDockerResponse(project, aiResponse);
    }

    public DockerGenerationResultDTO regenerateWithPrompt(ProjectEntity project, String currentContent, String userPrompt) {
        String prompt = String.format("""
            You are a Docker expert. Modify the existing Dockerfile based on the user's requirements.
            
            IMPORTANT: Keep all the original content and structure unless specifically asked to change it.
            Only make the changes requested by the user.
            
            Current Dockerfile:
            %s
            
            User requested changes:
            %s
            
            Instructions:
            1. Apply ONLY the changes requested by the user
            2. Preserve all other aspects of the Dockerfile
            3. If user asks to add comments, add them at the end
            4. Return ONLY the complete Dockerfile content without any markdown formatting or explanations
            5. Do not wrap the response in code blocks or add any preamble
            
            Return the complete modified Dockerfile:
            """, currentContent, userPrompt);

        String aiResponse = geminiService.generateContent(prompt);
        return processDockerResponse(project, aiResponse);
    }

    private String createDockerPrompt(ProjectEntity project, ProjectAnalysisDTO analysis, String currentContent) {
        return String.format("""
            Create an optimized Dockerfile for this project:
            
            Project: %s
            Type: %s
            Main Language: %s
            Build Tool: %s
            Architecture: %s
            Key Files: %s
            Dependencies: %s
            
            Current Dockerfile (if exists):
            %s
            
            Please create a production-ready Dockerfile with:
            - Multi-stage build if applicable
            - Proper layer caching
            - Security best practices
            - Minimal image size
            - Environment configuration
            
            Return only the Dockerfile content without explanations.
            """,
                project.getTitle(),
                analysis.getProjectType(),
                analysis.getMainLanguage(),
                analysis.getBuildTool(),
                analysis.getArchitectureType(),
                analysis.getKeyFiles(),
                analysis.getDependencies(),
                currentContent
        );
    }

    private DockerGenerationResultDTO processDockerResponse(ProjectEntity project, String aiResponse) {
        try {
            log.info("Raw Docker AI Response: {}", aiResponse);
            ObjectMapper mapper = new ObjectMapper();
            JsonNode rootNode = mapper.readTree(aiResponse);
            JsonNode textNode = rootNode.path("candidates")
                    .get(0)
                    .path("content")
                    .path("parts")
                    .get(0)
                    .path("text");

            String dockerContent = textNode.asText()
                    .replaceAll("```dockerfile\\n?", "")
                    .replaceAll("```docker\\n?", "")
                    .replaceAll("```\\n?", "")
                    .replaceAll("^#.*\\n?", "")
                    .trim();

            log.info("Extracted Docker content: {}", dockerContent);

            return DockerGenerationResultDTO.builder()
                    .projectId(project.getId())
                    .content(dockerContent)
                    .changeSummary("Dockerfile generated based on project analysis")
                    .isAutoGenerated(true)
                    .build();

        } catch (Exception e) {
            log.error("Error processing Docker AI response", e);
            return createDefaultDockerfile(project);
        }
    }

    private String cleanDockerContent(String content) {
        // Remove markdown code blocks
        String cleaned = content
                .replaceAll("```dockerfile\\s*\\n?", "")
                .replaceAll("```docker\\s*\\n?", "")
                .replaceAll("```\\s*\\n?", "")
                .trim();

        // Remove any leading explanatory text before FROM
        String[] lines = cleaned.split("\n");
        StringBuilder result = new StringBuilder();
        boolean foundFrom = false;

        for (String line : lines) {
            if (!foundFrom && line.trim().toUpperCase().startsWith("FROM")) {
                foundFrom = true;
            }
            if (foundFrom) {
                result.append(line).append("\n");
            }
        }

        return foundFrom ? result.toString().trim() : cleaned;
    }

    private String extractDockerContentFallback(String content) {
        // Try to find FROM instruction and extract from there
        String[] lines = content.split("\n");
        StringBuilder dockerfile = new StringBuilder();
        boolean inDockerfile = false;

        for (String line : lines) {
            String trimmedLine = line.trim().toUpperCase();
            if (trimmedLine.startsWith("FROM ")) {
                inDockerfile = true;
            }
            if (inDockerfile) {
                dockerfile.append(line).append("\n");
            }
        }

        String result = dockerfile.toString().trim();
        return result.isEmpty() ? content : result;
    }

    private String extractDockerContent(String aiResponse) {
        // Clean up AI response to get pure Dockerfile content
        return aiResponse.replaceAll("```dockerfile\\n?", "")
                .replaceAll("```\\n?", "")
                .replaceAll("^.*Dockerfile.*\\n", "")
                .trim();
    }

    private DockerGenerationResultDTO createDefaultDockerfile(ProjectEntity project) {
        String defaultContent = """
            FROM node:18-alpine
            
            WORKDIR /app
            
            # Copy package files
            COPY package*.json ./
            
            # Install dependencies
            RUN npm install
            
            # Copy application files
            COPY . .
            
            # Expose port
            EXPOSE 3000
            
            # Start application
            CMD ["npm", "start"]
            """;

        return DockerGenerationResultDTO.builder()
                .projectId(project.getId())
                .content(defaultContent)
                .changeSummary("Default Dockerfile created")
                .isAutoGenerated(true)
                .build();
    }
}
