package research.project.documate.backend.Backend.Service.AiService;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import research.project.documate.backend.Backend.DTOs.Readme.GitDiffAnalysisDTO;
import research.project.documate.backend.Backend.DTOs.Project.ProjectAnalysisDTO;
import research.project.documate.backend.Backend.DTOs.Readme.ReadmeGenerationResultDTO;
import research.project.documate.backend.Backend.Entity.ProjectEntity;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

@Service
@Slf4j
@AllArgsConstructor
public class ReadmeAiService {
    private final GeminiService geminiService;

    public ReadmeGenerationResultDTO generateReadme(ProjectEntity project, ProjectAnalysisDTO analysis) {
        String prompt = createDomainSpecificPrompt(project, analysis);
        String aiResponse = geminiService.generateContent(prompt);
        log.info("Response from AI: {}", aiResponse);
        return processAiResponse(project, aiResponse);
    }

    private ReadmeGenerationResultDTO processAiResponse(ProjectEntity project, String aiResponse) {
        try {
            log.info("Raw AI Response: {}", aiResponse);
            // Extract JSON from the response
            String jsonContent = extractJsonFromResponse(aiResponse);
            log.info("Extracted JSON content: {}", jsonContent);

            if (jsonContent == null || jsonContent.trim().isEmpty()) {
                log.warn("No JSON content found in AI response, using default README");
                return createDefaultReadme(project);
            }

            ObjectMapper mapper = new ObjectMapper();
            JsonNode readmeJson = mapper.readTree(jsonContent);

            // FLEXIBLE FIELD EXTRACTION - CHANGES START HERE
            String readmeContent = extractReadmeContent(readmeJson);
            String changeSummary = extractChangeSummary(readmeJson);

            if (readmeContent == null || readmeContent.trim().isEmpty()) {
                log.warn("Empty readme content in AI response, using default");
                return createDefaultReadme(project);
            }

            List<String> keyFeatures = extractKeyFeatures(readmeJson);
            List<String> setupSteps = extractSetupSteps(readmeJson);
            // FLEXIBLE FIELD EXTRACTION - CHANGES END HERE

            return ReadmeGenerationResultDTO.builder()
                    .projectId(project.getId())
                    .content(readmeContent)
                    .changeSummary(changeSummary)
                    .keyFeatures(keyFeatures)
                    .setupSteps(setupSteps)
                    .isAutoGenerated(true)
                    .build();

        } catch (Exception e) {
            log.error("Error processing AI response: {}", e.getMessage(), e);
            log.info("Falling back to default README due to parsing error");
            return createDefaultReadme(project);
        }
    }

    private String extractReadmeContent(JsonNode readmeJson) {
        // Try different possible field names for readme content
        String[] possibleFields = {"readme_content", "readme", "content", "markdown", "readmeContent"};

        for (String field : possibleFields) {
            if (readmeJson.has(field)) {
                String content = readmeJson.path(field).asText();
                if (content != null && !content.trim().isEmpty()) {
                    log.info("Found readme content in field: '{}'", field);
                    return content;
                }
            }
        }

        // If no specific field found, check if the root is a string (direct markdown)
        if (readmeJson.isTextual()) {
            return readmeJson.asText();
        }

        return null;
    }

    private String extractChangeSummary(JsonNode readmeJson) {
        // Try different possible field names for change summary
        String[] possibleFields = {"change_summary", "changeSummary", "summary", "changes", "description"};

        for (String field : possibleFields) {
            if (readmeJson.has(field)) {
                String summary = readmeJson.path(field).asText();
                if (summary != null && !summary.trim().isEmpty()) {
                    log.info("Found change summary in field: '{}'", field);
                    return summary;
                }
            }
        }

        return "Updated README based on recent code changes";
    }

    private String extractJsonFromResponse(String aiResponse) {
        try {
            //parse the entire response as JSON first
            ObjectMapper mapper = new ObjectMapper();
            JsonNode rootNode = mapper.readTree(aiResponse);
            //If it's the full Gemini response structure
            if (rootNode.has("candidates")) {
                JsonNode textNode = rootNode.path("candidates")
                        .get(0)
                        .path("content")
                        .path("parts")
                        .get(0)
                        .path("text");
                String textContent = textNode.asText();
                return extractJsonFromText(textContent);
            }

            return aiResponse; // If it's already the JSON we need

        } catch (Exception e) {
            log.info("Full response is not JSON, trying to extract JSON from text");
            return extractJsonFromText(aiResponse);
        }
    }

    private String extractJsonFromText(String textContent) {
        if (textContent == null) {
            return null;
        }

        String cleaned = textContent // Remove code block markers
                .replaceAll("```json\\n?", "")
                .replaceAll("\\n?```", "")
                .replaceAll("```\\n?", "")
                .trim();

        log.info("Cleaned text content: {}", cleaned);

        int startBrace = cleaned.indexOf('{'); // Try to find JSON object boundaries
        int lastBrace = cleaned.lastIndexOf('}');

        if (startBrace != -1 && lastBrace != -1 && lastBrace > startBrace) {
            String jsonCandidate = cleaned.substring(startBrace, lastBrace + 1);
            log.info("Extracted JSON candidate: {}", jsonCandidate);

            try { // Validate it's proper JSON
                ObjectMapper mapper = new ObjectMapper();
                mapper.readTree(jsonCandidate);
                return jsonCandidate;
            } catch (Exception e) {
                log.warn("Extracted text is not valid JSON: {}", e.getMessage());
            }
        }

        log.info("No JSON structure found, treating as markdown content"); // If no JSON found, return the cleaned text as markdown content
        return "{\"readme_content\": \"" + escapeJson(cleaned) + "\", \"change_summary\": \"AI generated README\"}";
    }

    private String escapeJson(String text) {
        return text.replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r")
                .replace("\t", "\\t");
    }

    private ReadmeGenerationResultDTO createDefaultReadme(ProjectEntity project) {
        String defaultContent = String.format(
                "# %s\n\n" +
                        "## Description\nA project created with DocuMate.\n\n" +
                        "## Setup\nPlease configure your project setup instructions here.\n\n" +
                        "## Usage\nAdd usage instructions here.",
                project.getTitle()
        );

        return ReadmeGenerationResultDTO.builder()
                .projectId(project.getId())
                .content(defaultContent)
                .changeSummary("Initial project setup")
                .keyFeatures(Arrays.asList("Feature 1", "Feature 2"))
                .setupSteps(Arrays.asList("Step 1: Clone repository", "Step 2: Install dependencies"))
                .isAutoGenerated(true)
                .build();
    }

    private List<String> extractKeyFeatures(JsonNode readmeJson) {
        // Try different possible field names for key features
        String[] possibleFields = {"key_features", "keyFeatures", "features", "key_points"};

        for (String field : possibleFields) {
            if (readmeJson.has(field) && readmeJson.path(field).isArray()) {
                List<String> features = new ArrayList<>();
                readmeJson.path(field).forEach(feature -> features.add(feature.asText()));
                if (!features.isEmpty()) {
                    log.info("Found key features in field: '{}'", field);
                    return features;
                }
            }
        }

        return Arrays.asList("Key features will be added here");
    }

    private List<String> extractSetupSteps(JsonNode readmeJson) {
        // Try different possible field names for setup steps
        String[] possibleFields = {"setup_steps", "setupSteps", "installation", "setup", "steps"};

        for (String field : possibleFields) {
            if (readmeJson.has(field) && readmeJson.path(field).isArray()) {
                List<String> steps = new ArrayList<>();
                readmeJson.path(field).forEach(step -> steps.add(step.asText()));
                if (!steps.isEmpty()) {
                    log.info("Found setup steps in field: '{}'", field);
                    return steps;
                }
            }
        }

        return Arrays.asList("Setup steps will be added here");
    }

    private String createDomainSpecificPrompt(ProjectEntity project, ProjectAnalysisDTO analysis) {
        String domainGroup = project.getTemplate().getDomainGroup();

        String domainSpecificInstructions = getDomainInstructions(domainGroup, analysis);
        String readmeStructure = getDomainReadmeStructure(domainGroup);

        return String.format("""
            %s
            
            Project Details:
            Project Name: %s
            Repository: %s
            Template Domain: %s
            Specific Template: %s
            Project Type: %s
            Architecture: %s
            Main Language: %s
            Build Tool: %s
            Key Files: %s
            Sub-projects: %s
            Dependencies: %s
            File Structure: %s
            
            Create a professional README.md following this structure:
            %s
            
            Ensure the response follows the EXACT JSON format shown above.
            """,
                domainSpecificInstructions,
                project.getTitle(),
                project.getGitRepoLink(),
                domainGroup,
                project.getTemplate().getDisplayName(),
                analysis.getProjectType(),
                analysis.getArchitectureType(),
                analysis.getMainLanguage(),
                analysis.getBuildTool(),
                analysis.getKeyFiles(),
                analysis.getSubProjects(),
                analysis.getDependencies(),
                analysis.getFileStructure(),
                readmeStructure
        );
    }

    private String getDomainInstructions(String domainGroup, ProjectAnalysisDTO analysis) {
        switch (domainGroup) {
            case "AI_DATA":
                return """
                    Analyze this AI/Data project and generate a comprehensive README.md in the following EXACT JSON format:
                    {
                        "readme_content": "Full README.md content in markdown format",
                        "change_summary": "Brief summary of AI models, data pipelines, or ML capabilities",
                        "key_features": [
                            "Feature 1",
                            "Feature 2"
                        ],
                        "setup_steps": [
                            "Step 1 description",
                            "Step 2 description"
                        ]
                    }
                    
                    Focus on: AI models, datasets, training procedures, evaluation metrics, data preprocessing, model deployment.
                    """;

            case "WEB_SOFTWARE":
                return """
                    Analyze this Web/Mobile/Software project and generate a comprehensive README.md in the following EXACT JSON format:
                    {
                        "readme_content": "Full README.md content in markdown format",
                        "change_summary": "Brief summary of application functionality and architecture",
                        "key_features": [
                            "Feature 1",
                            "Feature 2"
                        ],
                        "setup_steps": [
                            "Step 1 description",
                            "Step 2 description"
                        ]
                    }
                    
                    Focus on: User interface, APIs, database design, deployment instructions, development setup.
                    """;

            case "CLOUD_INFRA":
                return """
                    Analyze this Cloud/Infrastructure project and generate a comprehensive README.md in the following EXACT JSON format:
                    {
                        "readme_content": "Full README.md content in markdown format",
                        "change_summary": "Brief summary of infrastructure, deployment, and security features",
                        "key_features": [
                            "Feature 1",
                            "Feature 2"
                        ],
                        "setup_steps": [
                            "Step 1 description",
                            "Step 2 description"
                        ]
                    }
                    
                    Focus on: Infrastructure as code, deployment pipelines, security measures, monitoring, scaling.
                    """;

            case "EMERGING_TECH":
                return """
                    Analyze this Emerging Technology project and generate a comprehensive README.md in the following EXACT JSON format:
                    {
                        "readme_content": "Full README.md content in markdown format",
                        "change_summary": "Brief summary of innovative technology implementation",
                        "key_features": [
                            "Feature 1",
                            "Feature 2"
                        ],
                        "setup_steps": [
                            "Step 1 description",
                            "Step 2 description"
                        ]
                    }
                    
                    Focus on: Blockchain smart contracts, game mechanics, innovative algorithms, unique capabilities.
                    """;

            default:
                return getDomainInstructions("WEB_SOFTWARE", analysis);
        }
    }

    private String getDomainReadmeStructure(String domainGroup) {
        switch (domainGroup) {
            case "AI_DATA":
                return """
                    - Project Title & Badges
                    - Description & Purpose
                    - Features & Capabilities
                    - Installation & Setup
                    - Dataset Information
                    - Model Training
                    - Usage Examples
                    - API Documentation (if any)
                    - Evaluation Metrics
                    - Contributing
                    - License
                    """;

            case "WEB_SOFTWARE":
                return """
                    - Project Title & Badges
                    - Description
                    - Features
                    - Screenshots/Demos
                    - Installation
                    - Configuration
                    - Usage
                    - API Reference
                    - Tests
                    - Deployment
                    - Contributing
                    - License
                    """;

            case "CLOUD_INFRA":
                return """
                    - Project Title & Badges
                    - Description
                    - Architecture Diagram
                    - Features
                    - Prerequisites
                    - Installation & Deployment
                    - Configuration
                    - Security
                    - Monitoring
                    - Troubleshooting
                    - Contributing
                    - License
                    """;

            case "EMERGING_TECH":
                return """
                    - Project Title & Badges
                    - Description
                    - Features
                    - Technology Stack
                    - Installation
                    - Usage
                    - Smart Contracts/Game Rules
                    - Testing
                    - Deployment
                    - Contributing
                    - License
                    """;

            default:
                return getDomainReadmeStructure("WEB_SOFTWARE");
        }
    }

    public ReadmeGenerationResultDTO generateUpdatedReadme(ProjectEntity project, String currentContent, GitDiffAnalysisDTO diffAnalysis) {
        String prompt = createUpdatePrompt(project, currentContent, diffAnalysis);
        String aiResponse = geminiService.generateContent(prompt);
        return processAiResponse(project, aiResponse);
    }

    private String createUpdatePrompt(ProjectEntity project, String currentContent, GitDiffAnalysisDTO diffAnalysis) {
        return String.format("""
            You are a technical writer. Update the existing README based on recent code changes.
            
            CURRENT README CONTENT:
            %s
            
            RECENT CODE CHANGES:
            - Files changed: %d
            - Modified files: %s
            - Change summary: %s
            
            PROJECT: %s (%s)
            
            IMPORTANT: Return your response in EXACTLY this JSON format:
            {
                "readme_content": "Full updated README content in markdown format",
                "change_summary": "Brief description of what changed",
                "key_features": ["feature1", "feature2"],
                "setup_steps": ["step1", "step2"]
            }
            
            Do NOT include any other text outside this JSON structure.
            """,
                currentContent,
                diffAnalysis.getFilesChanged(),
                diffAnalysis.getModifiedFiles(),
                diffAnalysis.getChangeSummary(),
                project.getTitle(),
                project.getTemplate().getDisplayName()
        );
    }

    public ReadmeGenerationResultDTO regenerateWithPrompt(ProjectEntity project, String enhancedPrompt) {
        String fullPrompt = String.format("""
            Please improve this README based on user feedback:
            
            Current README:
            %s
            
            Please provide the improved README in the same JSON format.
            """, enhancedPrompt);

        return processAiResponse(project, geminiService.generateContent(fullPrompt));
    }
    private String getUserRequestPart(String enhancedPrompt) {
        if (enhancedPrompt.contains("User requested changes:")) { // Extract user request part from the enhanced prompt
            return enhancedPrompt.split("User requested changes:")[1].trim();
        }
        return enhancedPrompt;
    }
}
