package research.project.documate.backend.Backend.Service;

import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import research.project.documate.backend.Backend.DTOs.Docker.*;
import research.project.documate.backend.Backend.DTOs.Project.ProjectAnalysisDTO;
import research.project.documate.backend.Backend.Entity.DockerFileEntity;
import research.project.documate.backend.Backend.Entity.ProjectEntity;
import research.project.documate.backend.Backend.Repository.DockerFileRepository;
import research.project.documate.backend.Backend.Repository.ProjectRepository;
import research.project.documate.backend.Backend.Service.AiService.DockerAiService;
import research.project.documate.backend.Backend.Service.Support.ProjectAnalysisService;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.time.LocalDateTime;
import java.util.Optional;

@Service
@Slf4j
@AllArgsConstructor
public class DockerFileService {
    private final DockerFileRepository dockerFileRepository;
    private final ProjectRepository projectRepository;
    private final ProjectAnalysisService projectAnalysisService;
    private final DockerAiService dockerAiService;

    public DockerFileResponseDTO getCurrentDockerFile(Long projectId) { // 1. Check current Dockerfile
        ProjectEntity project = projectRepository.findById(projectId)
                .orElseThrow(() -> new RuntimeException("Project not found"));

        boolean dockerfileExists = checkDockerfileExists(project);

        Optional<DockerFileEntity> dockerFileOpt = dockerFileRepository.findLatestByProjectId(projectId); // Get latest (any status)

        if (dockerFileOpt.isPresent()) {
            DockerFileEntity dockerFile = dockerFileOpt.get();
            return DockerFileResponseDTO.builder()
                    .id(dockerFile.getId())
                    .content(dockerFile.getContent())
                    .exists(dockerfileExists)
                    .status(dockerFile.getCommitHash().startsWith("PENDING_") ? "PENDING" : "APPROVED")
                    .createdAt(dockerFile.getCreatedAt())
                    .build();
        } else {
            return DockerFileResponseDTO.builder()
                    .content("")
                    .exists(dockerfileExists)
                    .status("NONE")
                    .build();
        }
    }

    public DockerFileDiffDTO generateDockerFile(Long projectId) { // 2. Generate new Dockerfile (PENDING only)
        ProjectEntity project = projectRepository.findById(projectId)
                .orElseThrow(() -> new RuntimeException("Project not found"));

        ProjectAnalysisDTO analysis = projectAnalysisService.analyzeProject(project.getLocalPath());
        String currentContent = getCurrentDockerContent(project);

        DockerGenerationResultDTO newDocker = dockerAiService.generateDockerFile(project, analysis, currentContent);

        String oldContent = dockerFileRepository.findActiveByProjectId(projectId) // Get current approved for comparison
                .map(DockerFileEntity::getContent)
                .orElse("");

        DockerFileEntity pendingDocker = DockerFileEntity.builder() // Save as PENDING
                .project(project)
                .content(newDocker.getContent())
                .commitHash("PENDING_" + System.currentTimeMillis())
                .isAutoGenerated(true)
                .createdAt(LocalDateTime.now())
                .build();
        dockerFileRepository.save(pendingDocker);

        return DockerFileDiffDTO.builder()
                .oldContent(oldContent)
                .newContent(newDocker.getContent())
                .changeSummary("Dockerfile generated based on project analysis")
                .projectId(projectId)
                .build();
    }

    public DockerFileDiffDTO getDockerFileDiff(Long projectId) { // 3. Get diff between approved and pending
        try {
            log.info("=== DOCKER DIFF DEBUG ===");
            log.info("Project ID: {}", projectId);

            ProjectEntity project = projectRepository.findById(projectId)
                    .orElseThrow(() -> new RuntimeException("Project not found"));
            log.info("Project found: {}", project.getTitle());

            Optional<DockerFileEntity> approvedOpt = dockerFileRepository.findActiveByProjectId(projectId); // Get approved (old)
            log.info("Approved Dockerfile present: {}", approvedOpt.isPresent());

            String oldContent = approvedOpt.map(DockerFileEntity::getContent).orElse("");
            log.info("Old content length: {}", oldContent.length());

            Optional<DockerFileEntity> pendingOpt = dockerFileRepository.findByProjectIdAndCommitHashStartingWith(projectId, "PENDING_"); // Get pending (new)
            log.info("Pending Dockerfile present: {}", pendingOpt.isPresent());

            DockerFileEntity pendingDocker = pendingOpt
                    .orElseThrow(() -> new RuntimeException("No pending Dockerfile found. Please generate one first."));

            log.info("New content length: {}", pendingDocker.getContent().length());
            log.info("=== END DEBUG ===");

            return DockerFileDiffDTO.builder()
                    .oldContent(oldContent)
                    .newContent(pendingDocker.getContent())
                    .changeSummary("Dockerfile changes pending approval")
                    .projectId(projectId)
                    .build();

        } catch (Exception e) {
            log.error("Error in getDockerFileDiff for project {}: {}", projectId, e.getMessage(), e);
            throw new RuntimeException("Error getting Docker diff: " + e.getMessage());
        }
    }

    public String approveAndWriteDockerFile(Long projectId, DockerFilePushDTO pushRequest) { // 4. Write to file and approve
        ProjectEntity project = projectRepository.findById(projectId)
                .orElseThrow(() -> new RuntimeException("Project not found"));

        DockerFileEntity pendingDocker = dockerFileRepository.findByProjectIdAndCommitHashStartingWith(projectId, "PENDING_")
                .orElseThrow(() -> new RuntimeException("No pending Dockerfile found"));

        pendingDocker.setContent(pushRequest.getContent()); // Update content if modified

        writeDockerfileToProject(project, pushRequest.getContent()); // Write to file

        pendingDocker.setCommitHash("APPROVED_" + System.currentTimeMillis()); // Mark as approved
        dockerFileRepository.save(pendingDocker);

        return "Dockerfile approved and written successfully";
    }

    public DockerFileDiffDTO regenerateWithPrompt(Long projectId, DockerRegenerateRequestDTO request) { // 5. Regenerate with prompt
        ProjectEntity project = projectRepository.findById(projectId)
                .orElseThrow(() -> new RuntimeException("Project not found"));

        DockerGenerationResultDTO newResult = dockerAiService.regenerateWithPrompt(
                project, request.getCurrentContent(), request.getUserPrompt());

        DockerFileEntity pendingDocker = dockerFileRepository.findByProjectIdAndCommitHashStartingWith(projectId, "PENDING_") // Update or create pending
                .orElse(DockerFileEntity.builder()
                        .project(project)
                        .commitHash("PENDING_" + System.currentTimeMillis())
                        .isAutoGenerated(true)
                        .createdAt(LocalDateTime.now())
                        .build());

        pendingDocker.setContent(newResult.getContent());
        dockerFileRepository.save(pendingDocker);

        return DockerFileDiffDTO.builder()
                .oldContent(request.getCurrentContent())
                .newContent(newResult.getContent())
                .changeSummary("Regenerated: " + request.getUserPrompt())
                .projectId(projectId)
                .build();
    }

    private boolean checkDockerfileExists(ProjectEntity project) { // Helper methods
        try {
            return Files.exists(Paths.get(project.getLocalPath(), "Dockerfile"));
        } catch (Exception e) {
            return false;
        }
    }

    private String getCurrentDockerContent(ProjectEntity project) {
        try {
            Path dockerPath = Paths.get(project.getLocalPath(), "Dockerfile");
            if (Files.exists(dockerPath)) {
                return Files.readString(dockerPath);
            }
        } catch (Exception e) {
            log.warn("Error reading Dockerfile", e);
        }
        return "";
    }

    private void writeDockerfileToProject(ProjectEntity project, String content) {
        try {
            Path dockerPath = Paths.get(project.getLocalPath(), "Dockerfile");
            Files.write(dockerPath, content.getBytes(),
                    StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
            log.info("Dockerfile written to: {}", dockerPath);
        } catch (IOException e) {
            throw new RuntimeException("Failed to write Dockerfile", e);
        }
    }
}
