package research.project.documate.backend.Backend.Service;

import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import research.project.documate.backend.Backend.DTOs.EnvExample.*;
import research.project.documate.backend.Backend.DTOs.Project.ProjectAnalysisDTO;
import research.project.documate.backend.Backend.Entity.EnvExampleFileEntity;
import research.project.documate.backend.Backend.Entity.ProjectEntity;
import research.project.documate.backend.Backend.Repository.EnvExampleFileRepository;
import research.project.documate.backend.Backend.Repository.ProjectRepository;
import research.project.documate.backend.Backend.Service.AiService.EnvExampleAiService;
import research.project.documate.backend.Backend.Service.Support.ProjectAnalysisService;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.time.LocalDateTime;
import java.util.Optional;

@Service
@Slf4j
@AllArgsConstructor
public class EnvExampleFileService {
    private final EnvExampleFileRepository envExampleFileRepository;
    private final ProjectRepository projectRepository;
    private final ProjectAnalysisService projectAnalysisService;
    private final EnvExampleAiService envExampleAiService;

    public EnvExampleFileResponseDTO getCurrentEnvExample(Long projectId) {
        ProjectEntity project = projectRepository.findById(projectId)
                .orElseThrow(() -> new RuntimeException("Project not found"));

        boolean envExampleExists = checkEnvExampleExists(project);

        Optional<EnvExampleFileEntity> envExampleOpt = envExampleFileRepository.findLatestByProjectId(projectId);

        if (envExampleOpt.isPresent()) {
            EnvExampleFileEntity envExampleFile = envExampleOpt.get();
            return EnvExampleFileResponseDTO.builder()
                    .id(envExampleFile.getId())
                    .content(envExampleFile.getContent())
                    .exists(envExampleExists)
                    .status(envExampleFile.getCommitHash().startsWith("PENDING_") ? "PENDING" : "APPROVED")
                    .createdAt(envExampleFile.getCreatedAt())
                    .build();
        } else {
            return EnvExampleFileResponseDTO.builder()
                    .content("")
                    .exists(envExampleExists)
                    .status("NONE")
                    .build();
        }
    }

    public EnvExampleFileDiffDTO generateEnvExample(Long projectId) {
        ProjectEntity project = projectRepository.findById(projectId)
                .orElseThrow(() -> new RuntimeException("Project not found"));

        ProjectAnalysisDTO analysis = projectAnalysisService.analyzeProject(project.getLocalPath());
        String currentContent = getCurrentEnvExampleContent(project);

        EnvExampleGenerationResultDTO newEnvExample = envExampleAiService.generateEnvExample(project, analysis, currentContent);

        String oldContent = envExampleFileRepository.findActiveByProjectId(projectId)
                .map(EnvExampleFileEntity::getContent)
                .orElse("");

        EnvExampleFileEntity pendingEnvExample = EnvExampleFileEntity.builder()
                .project(project)
                .content(newEnvExample.getContent())
                .commitHash("PENDING_" + System.currentTimeMillis())
                .isAutoGenerated(true)
                .createdAt(LocalDateTime.now())
                .build();
        envExampleFileRepository.save(pendingEnvExample);

        return EnvExampleFileDiffDTO.builder()
                .oldContent(oldContent)
                .newContent(newEnvExample.getContent())
                .changeSummary(".env.example generated based on project analysis")
                .projectId(projectId)
                .build();
    }

    public EnvExampleFileDiffDTO getEnvExampleDiff(Long projectId) {
        try {
            log.info("=== ENV EXAMPLE DIFF DEBUG ===");
            log.info("Project ID: {}", projectId);

            ProjectEntity project = projectRepository.findById(projectId)
                    .orElseThrow(() -> new RuntimeException("Project not found"));
            log.info("Project found: {}", project.getTitle());

            Optional<EnvExampleFileEntity> approvedOpt = envExampleFileRepository.findActiveByProjectId(projectId);
            log.info("Approved EnvExample present: {}", approvedOpt.isPresent());

            String oldContent = approvedOpt.map(EnvExampleFileEntity::getContent).orElse("");
            log.info("Old content length: {}", oldContent.length());

            Optional<EnvExampleFileEntity> pendingOpt = envExampleFileRepository.findByProjectIdAndCommitHashStartingWith(projectId, "PENDING_");
            log.info("Pending EnvExample present: {}", pendingOpt.isPresent());

            EnvExampleFileEntity pendingEnvExample = pendingOpt
                    .orElseThrow(() -> new RuntimeException("No pending .env.example found. Please generate one first."));

            log.info("New content length: {}", pendingEnvExample.getContent().length());
            log.info("=== END DEBUG ===");

            return EnvExampleFileDiffDTO.builder()
                    .oldContent(oldContent)
                    .newContent(pendingEnvExample.getContent())
                    .changeSummary(".env.example changes pending approval")
                    .projectId(projectId)
                    .build();

        } catch (Exception e) {
            log.error("Error in getEnvExampleDiff for project {}: {}", projectId, e.getMessage(), e);
            throw new RuntimeException("Error getting .env.example diff: " + e.getMessage());
        }
    }

    public String approveAndWriteEnvExample(Long projectId, EnvExampleFilePushDTO pushRequest) {
        ProjectEntity project = projectRepository.findById(projectId)
                .orElseThrow(() -> new RuntimeException("Project not found"));

        EnvExampleFileEntity pendingEnvExample = envExampleFileRepository.findByProjectIdAndCommitHashStartingWith(projectId, "PENDING_")
                .orElseThrow(() -> new RuntimeException("No pending .env.example found"));

        pendingEnvExample.setContent(pushRequest.getContent());

        writeEnvExampleToProject(project, pushRequest.getContent());

        pendingEnvExample.setCommitHash("APPROVED_" + System.currentTimeMillis());
        envExampleFileRepository.save(pendingEnvExample);

        return ".env.example approved and written successfully";
    }

    public EnvExampleFileDiffDTO regenerateWithPrompt(Long projectId, EnvExampleRegenerateRequestDTO request) {
        ProjectEntity project = projectRepository.findById(projectId)
                .orElseThrow(() -> new RuntimeException("Project not found"));

        EnvExampleGenerationResultDTO newResult = envExampleAiService.regenerateWithPrompt(
                project, request.getCurrentContent(), request.getUserPrompt());

        EnvExampleFileEntity pendingEnvExample = envExampleFileRepository.findByProjectIdAndCommitHashStartingWith(projectId, "PENDING_")
                .orElse(EnvExampleFileEntity.builder()
                        .project(project)
                        .commitHash("PENDING_" + System.currentTimeMillis())
                        .isAutoGenerated(true)
                        .createdAt(LocalDateTime.now())
                        .build());

        pendingEnvExample.setContent(newResult.getContent());
        envExampleFileRepository.save(pendingEnvExample);

        return EnvExampleFileDiffDTO.builder()
                .oldContent(request.getCurrentContent())
                .newContent(newResult.getContent())
                .changeSummary("Regenerated: " + request.getUserPrompt())
                .projectId(projectId)
                .build();
    }

    private boolean checkEnvExampleExists(ProjectEntity project) {
        try {
            return Files.exists(Paths.get(project.getLocalPath(), ".env.example"));
        } catch (Exception e) {
            return false;
        }
    }

    private String getCurrentEnvExampleContent(ProjectEntity project) {
        try {
            Path envExamplePath = Paths.get(project.getLocalPath(), ".env.example");
            if (Files.exists(envExamplePath)) {
                return Files.readString(envExamplePath);
            }
        } catch (Exception e) {
            log.warn("Error reading .env.example", e);
        }
        return "";
    }

    private void writeEnvExampleToProject(ProjectEntity project, String content) {
        try {
            Path envExamplePath = Paths.get(project.getLocalPath(), ".env.example");
            Files.write(envExamplePath, content.getBytes(),
                    StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
            log.info(".env.example written to: {}", envExamplePath);
        } catch (IOException e) {
            throw new RuntimeException("Failed to write .env.example", e);
        }
    }
}
