package research.project.documate.backend.Backend.Service;

import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import research.project.documate.backend.Backend.DTOs.GitIgnore.*;
import research.project.documate.backend.Backend.DTOs.Project.ProjectAnalysisDTO;
import research.project.documate.backend.Backend.Entity.GitignoreFileEntity;
import research.project.documate.backend.Backend.Entity.ProjectEntity;
import research.project.documate.backend.Backend.Repository.GitignoreFileRepository;
import research.project.documate.backend.Backend.Repository.ProjectRepository;
import research.project.documate.backend.Backend.Service.AiService.GitignoreAiService;
import research.project.documate.backend.Backend.Service.Support.ProjectAnalysisService;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.time.LocalDateTime;
import java.util.Optional;

@Service
@Slf4j
@AllArgsConstructor
public class GitignoreFileService {
    private final GitignoreFileRepository gitignoreFileRepository;
    private final ProjectRepository projectRepository;
    private final ProjectAnalysisService projectAnalysisService;
    private final GitignoreAiService gitignoreAiService;

    public GitignoreFileResponseDTO getCurrentGitignore(Long projectId) {
        ProjectEntity project = projectRepository.findById(projectId)
                .orElseThrow(() -> new RuntimeException("Project not found"));

        boolean gitignoreExists = checkGitignoreExists(project);

        Optional<GitignoreFileEntity> gitignoreOpt = gitignoreFileRepository.findLatestByProjectId(projectId);

        if (gitignoreOpt.isPresent()) {
            GitignoreFileEntity gitignoreFile = gitignoreOpt.get();
            return GitignoreFileResponseDTO.builder()
                    .id(gitignoreFile.getId())
                    .content(gitignoreFile.getContent())
                    .exists(gitignoreExists)
                    .status(gitignoreFile.getCommitHash().startsWith("PENDING_") ? "PENDING" : "APPROVED")
                    .createdAt(gitignoreFile.getCreatedAt())
                    .build();
        } else {
            return GitignoreFileResponseDTO.builder()
                    .content("")
                    .exists(gitignoreExists)
                    .status("NONE")
                    .build();
        }
    }

    public GitignoreFileDiffDTO generateGitignore(Long projectId) {
        ProjectEntity project = projectRepository.findById(projectId)
                .orElseThrow(() -> new RuntimeException("Project not found"));

        ProjectAnalysisDTO analysis = projectAnalysisService.analyzeProject(project.getLocalPath());
        String currentContent = getCurrentGitignoreContent(project);

        GitignoreGenerationResultDTO newGitignore = gitignoreAiService.generateGitignore(project, analysis, currentContent);

        String oldContent = gitignoreFileRepository.findActiveByProjectId(projectId)
                .map(GitignoreFileEntity::getContent)
                .orElse("");

        GitignoreFileEntity pendingGitignore = GitignoreFileEntity.builder()
                .project(project)
                .content(newGitignore.getContent())
                .commitHash("PENDING_" + System.currentTimeMillis())
                .isAutoGenerated(true)
                .createdAt(LocalDateTime.now())
                .build();
        gitignoreFileRepository.save(pendingGitignore);

        return GitignoreFileDiffDTO.builder()
                .oldContent(oldContent)
                .newContent(newGitignore.getContent())
                .changeSummary(".gitignore generated based on project analysis")
                .projectId(projectId)
                .build();
    }

    public GitignoreFileDiffDTO getGitignoreDiff(Long projectId) {
        try {
            log.info("=== GITIGNORE DIFF DEBUG ===");
            log.info("Project ID: {}", projectId);

            ProjectEntity project = projectRepository.findById(projectId)
                    .orElseThrow(() -> new RuntimeException("Project not found"));
            log.info("Project found: {}", project.getTitle());

            Optional<GitignoreFileEntity> approvedOpt = gitignoreFileRepository.findActiveByProjectId(projectId);
            log.info("Approved Gitignore present: {}", approvedOpt.isPresent());

            String oldContent = approvedOpt.map(GitignoreFileEntity::getContent).orElse("");
            log.info("Old content length: {}", oldContent.length());

            Optional<GitignoreFileEntity> pendingOpt = gitignoreFileRepository.findByProjectIdAndCommitHashStartingWith(projectId, "PENDING_");
            log.info("Pending Gitignore present: {}", pendingOpt.isPresent());

            GitignoreFileEntity pendingGitignore = pendingOpt
                    .orElseThrow(() -> new RuntimeException("No pending .gitignore found. Please generate one first."));

            log.info("New content length: {}", pendingGitignore.getContent().length());
            log.info("=== END DEBUG ===");

            return GitignoreFileDiffDTO.builder()
                    .oldContent(oldContent)
                    .newContent(pendingGitignore.getContent())
                    .changeSummary(".gitignore changes pending approval")
                    .projectId(projectId)
                    .build();

        } catch (Exception e) {
            log.error("Error in getGitignoreDiff for project {}: {}", projectId, e.getMessage(), e);
            throw new RuntimeException("Error getting .gitignore diff: " + e.getMessage());
        }
    }

    public String approveAndWriteGitignore(Long projectId, GitignoreFilePushDTO pushRequest) {
        ProjectEntity project = projectRepository.findById(projectId)
                .orElseThrow(() -> new RuntimeException("Project not found"));

        GitignoreFileEntity pendingGitignore = gitignoreFileRepository.findByProjectIdAndCommitHashStartingWith(projectId, "PENDING_")
                .orElseThrow(() -> new RuntimeException("No pending .gitignore found"));

        pendingGitignore.setContent(pushRequest.getContent());

        writeGitignoreToProject(project, pushRequest.getContent());

        pendingGitignore.setCommitHash("APPROVED_" + System.currentTimeMillis());
        gitignoreFileRepository.save(pendingGitignore);

        return ".gitignore approved and written successfully";
    }

    public GitignoreFileDiffDTO regenerateWithPrompt(Long projectId, GitignoreRegenerateRequestDTO request) {
        ProjectEntity project = projectRepository.findById(projectId)
                .orElseThrow(() -> new RuntimeException("Project not found"));

        GitignoreGenerationResultDTO newResult = gitignoreAiService.regenerateWithPrompt(
                project, request.getCurrentContent(), request.getUserPrompt());

        GitignoreFileEntity pendingGitignore = gitignoreFileRepository.findByProjectIdAndCommitHashStartingWith(projectId, "PENDING_")
                .orElse(GitignoreFileEntity.builder()
                        .project(project)
                        .commitHash("PENDING_" + System.currentTimeMillis())
                        .isAutoGenerated(true)
                        .createdAt(LocalDateTime.now())
                        .build());

        pendingGitignore.setContent(newResult.getContent());
        gitignoreFileRepository.save(pendingGitignore);

        return GitignoreFileDiffDTO.builder()
                .oldContent(request.getCurrentContent())
                .newContent(newResult.getContent())
                .changeSummary("Regenerated: " + request.getUserPrompt())
                .projectId(projectId)
                .build();
    }

    private boolean checkGitignoreExists(ProjectEntity project) {
        try {
            return Files.exists(Paths.get(project.getLocalPath(), ".gitignore"));
        } catch (Exception e) {
            return false;
        }
    }

    private String getCurrentGitignoreContent(ProjectEntity project) {
        try {
            Path gitignorePath = Paths.get(project.getLocalPath(), ".gitignore");
            if (Files.exists(gitignorePath)) {
                return Files.readString(gitignorePath);
            }
        } catch (Exception e) {
            log.warn("Error reading .gitignore", e);
        }
        return "";
    }

    private void writeGitignoreToProject(ProjectEntity project, String content) {
        try {
            Path gitignorePath = Paths.get(project.getLocalPath(), ".gitignore");
            Files.write(gitignorePath, content.getBytes(),
                    StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
            log.info(".gitignore written to: {}", gitignorePath);
        } catch (IOException e) {
            throw new RuntimeException("Failed to write .gitignore", e);
        }
    }
}
