package research.project.documate.backend.Backend.Service;

import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import research.project.documate.backend.Backend.DTOs.GitDiffAnalysisDTO;
import research.project.documate.backend.Backend.DTOs.GitPushEventDTO;
import research.project.documate.backend.Backend.DTOs.ReadmeGenerationResultDTO;
import research.project.documate.backend.Backend.Entity.ProjectEntity;
import research.project.documate.backend.Backend.Entity.ReadmeFileEntity;
import research.project.documate.backend.Backend.Repository.ProjectRepository;
import research.project.documate.backend.Backend.Repository.ReadmeFileRepository;

import java.time.LocalDateTime;

@Service
@Slf4j
@AllArgsConstructor
public class GitTriggerService {
    private final ProjectRepository projectRepository;
    private final ReadmeFileRepository readmeFileRepository;
    private final GitDiffService gitDiffService;
    private final ReadmeAiService readmeAiService;

    public void processGitPush(GitPushEventDTO pushEvent) {
        launchNotification("DocuMate System Started - Processing README update for: " + pushEvent.getProjectPath());

        ProjectEntity project = projectRepository.findByLocalPath(pushEvent.getProjectPath())  //Find project by path
                .orElseThrow(() -> new RuntimeException("Project not found"));

        ReadmeFileEntity currentReadme = readmeFileRepository.findByProject(project) //Get current README from DB
                .orElseThrow(() -> new RuntimeException("No README found for project"));

        GitDiffAnalysisDTO diffAnalysis = gitDiffService.analyzeChanges(project, pushEvent.getCommitHash()); // Analyze Git changes

        ReadmeGenerationResultDTO newReadme = readmeAiService.generateUpdatedReadme( // Generate new README
                project, currentReadme, diffAnalysis);

        ReadmeFileEntity updatedReadme = ReadmeFileEntity.builder() //Save new README to DB (but don't write file yet)
                .project(project)
                .content(newReadme.getContent())
                .commitHash(pushEvent.getCommitHash())
                .isAutoGenerated(true)
                .changeSummary(newReadme.getChangeSummary())
                .createdAt(LocalDateTime.now())
                .build();

        ReadmeFileEntity savedReadme = readmeFileRepository.save(updatedReadme);

        launchNotification("README generated successfully! View in DocuMate app. Project: " + project.getTitle());//Notify frontend via API to show diff view
    }
    private void launchNotification(String message) {
        try {
            String command;
            if (System.getProperty("os.name").toLowerCase().contains("windows")) {
                command = "cmd.exe /c mshta vbscript:Execute(\"msgbox \"\"" + message + "\"\"\":close\")";
            } else {
                command = "zenity --info --text=\"" + message + "\"";
            }

            ProcessBuilder builder = new ProcessBuilder(command.split(" "));
            builder.start();

        } catch (Exception e) {
            log.error("Failed to show popup", e);
        }
    }
}
