package research.project.documate.backend.Backend.Service;

import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import research.project.documate.backend.Backend.DTOs.GitDiffAnalysisDTO;
import research.project.documate.backend.Backend.DTOs.GitPushEventDTO;
import research.project.documate.backend.Backend.DTOs.ReadmeGenerationResultDTO;
import research.project.documate.backend.Backend.Entity.ProjectEntity;
import research.project.documate.backend.Backend.Entity.ReadmeFileEntity;
import research.project.documate.backend.Backend.Repository.ProjectRepository;
import research.project.documate.backend.Backend.Repository.ReadmeFileRepository;

import java.time.LocalDateTime;

@Service
@Slf4j
@AllArgsConstructor
public class GitTriggerService {
    private final ProjectRepository projectRepository;
    private final ReadmeFileRepository readmeFileRepository;
    private final GitDiffService gitDiffService;
    private final ReadmeAiService readmeAiService;

    public void processGitPush(GitPushEventDTO pushEvent) {
        // 1. Find project by path
        ProjectEntity project = projectRepository.findByLocalPath(pushEvent.getProjectPath())
                .orElseThrow(() -> new RuntimeException("Project not found"));

        // 2. Get current README from DB
        ReadmeFileEntity currentReadme = readmeFileRepository.findByProject(project)
                .orElseThrow(() -> new RuntimeException("No README found for project"));

        // 3. Analyze Git changes
        GitDiffAnalysisDTO diffAnalysis = gitDiffService.analyzeChanges(project, pushEvent.getCommitHash());

        // 4. Generate new README
        ReadmeGenerationResultDTO newReadme = readmeAiService.generateUpdatedReadme(
                project, currentReadme, diffAnalysis);

        // 5. Save new README to DB (but don't write file yet)
        ReadmeFileEntity updatedReadme = ReadmeFileEntity.builder()
                .project(project)
                .content(newReadme.getContent())
                .commitHash(pushEvent.getCommitHash())
                .isAutoGenerated(true)
                .changeSummary(newReadme.getChangeSummary())
                .createdAt(LocalDateTime.now())
                .build();

        ReadmeFileEntity savedReadme = readmeFileRepository.save(updatedReadme);

        // 6. Notify frontend (via WebSocket/API) to show diff view
        notifyFrontendForApproval(project, currentReadme, savedReadme);
    }

    private void notifyFrontendForApproval(ProjectEntity project, ReadmeFileEntity oldReadme, ReadmeFileEntity newReadme) {
        // This will trigger the Electron app to show diff view
        // You can use WebSocket or have frontend poll for updates
    }
}
