package research.project.documate.backend.Backend.Service;

import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import research.project.documate.backend.Backend.DTOs.GitDiffAnalysisDTO;
import research.project.documate.backend.Backend.DTOs.GitPushEventDTO;
import research.project.documate.backend.Backend.DTOs.ReadmeGenerationResultDTO;
import research.project.documate.backend.Backend.Entity.ProjectEntity;
import research.project.documate.backend.Backend.Entity.ReadmeFileEntity;
import research.project.documate.backend.Backend.Repository.ProjectRepository;
import research.project.documate.backend.Backend.Repository.ReadmeFileRepository;

import java.time.LocalDateTime;

@Service
@Slf4j
@AllArgsConstructor
public class GitTriggerService {
    private final ProjectRepository projectRepository;
    private final ReadmeFileRepository readmeFileRepository;
    private final GitDiffService gitDiffService;
    private final ReadmeAiService readmeAiService;

    public void processGitPush(GitPushEventDTO pushEvent) {
        try {
            launchNotification("DocuMate System Started - Processing README update for project ID: " + pushEvent.getProjectId());
            log.info("Looking up project with ID: {}", pushEvent.getProjectId());
            ProjectEntity project = projectRepository.findById(pushEvent.getProjectId())
                    .orElseThrow(() -> {
                        log.error("Project not found with ID: {}. Available projects:", pushEvent.getProjectId());
                        projectRepository.findAll().forEach(p ->
                                log.info(" - ID: {}, Title: {}, Path: {}", p.getId(), p.getTitle(), p.getLocalPath()));
                        return new RuntimeException("Project not found with ID: " + pushEvent.getProjectId());
                    });

            log.info("Found project: {} (ID: {})", project.getTitle(), project.getId());
            log.info("Looking up current README for project ID: {}", project.getId());
            ReadmeFileEntity currentReadme = readmeFileRepository.findByProjectId(project.getId())
                    .orElseThrow(() -> {
                        log.error("No README found for project ID: {}", project.getId());
                        return new RuntimeException("No README found for project");
                    });
            log.info("Found current README ID: {}", currentReadme.getId());

            GitDiffAnalysisDTO diffAnalysis = gitDiffService.analyzeChanges(project, pushEvent.getCommitHash());

            ReadmeGenerationResultDTO newReadme = readmeAiService.generateUpdatedReadme(
                    project, currentReadme, diffAnalysis);

            ReadmeFileEntity updatedReadme = ReadmeFileEntity.builder() // Save new README with pending status
                    .project(project)
                    .content(newReadme.getContent())
                    .commitHash("PENDING_" + pushEvent.getCommitHash())
                    .isAutoGenerated(true)
                    .changeSummary(newReadme.getChangeSummary())
                    .createdAt(LocalDateTime.now())
                    .build();

            log.info("Saving new README to database...");
            ReadmeFileEntity savedReadme = readmeFileRepository.save(updatedReadme);

            log.info("New README generated and saved with ID: {} for project: {}",
                    savedReadme.getId(), project.getTitle());
            launchNotification("README generated successfully! Project: " + project.getTitle());

        } catch (Exception e) {
            log.error("Error processing git push for project ID: {}", pushEvent.getProjectId(), e);
            launchNotification("Error processing README: " + e.getMessage());
            throw new RuntimeException("Error processing push", e);
        }
    }

    private void launchNotification(String message) {
        try {
            String command;
            if (System.getProperty("os.name").toLowerCase().contains("windows")) {
                command = "cmd.exe /c mshta vbscript:Execute(\"msgbox \"\"" + message + "\"\"\":close\")";
            } else {
                command = "zenity --info --text=\"" + message + "\"";
            }

            ProcessBuilder builder = new ProcessBuilder(command.split(" "));
            builder.start();

        } catch (Exception e) {
            log.error("Failed to show popup", e);
        }
    }
}
