package research.project.documate.backend.Backend.Service;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import research.project.documate.backend.Backend.DTOs.ProjectAnalysisDTO;
import research.project.documate.backend.Backend.DTOs.ProjectRegistrationDTO;
import research.project.documate.backend.Backend.DTOs.ProjectResponseDTO;
import research.project.documate.backend.Backend.DTOs.ReadmeGenerationResultDTO;
import research.project.documate.backend.Backend.Entity.ProjectEntity;
import research.project.documate.backend.Backend.Entity.ReadmeFileEntity;
import research.project.documate.backend.Backend.Repository.ProjectRepository;
import research.project.documate.backend.Backend.Repository.ReadmeFileRepository;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

@Service
@Slf4j
@AllArgsConstructor
@Builder
public class ProjectService {
    private final ProjectRepository projectRepository;
    private final ReadmeFileRepository readmeFileRepository;
    private final ProjectAnalysisService projectAnalysisService;
    private final ReadmeAiService readmeAiService;
    private final GitHookService gitHookService;

    public List<ProjectResponseDTO> getAllProjects() {
        return projectRepository.findAll()
                .stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());
    }

    private ProjectResponseDTO convertToDTO(ProjectEntity projectEntity) {
        ProjectResponseDTO dto = new ProjectResponseDTO();
        dto.setId(projectEntity.getId());
        dto.setTitle(projectEntity.getTitle());
        dto.setGitRepoLink(projectEntity.getGitRepoLink());
        dto.setLocalPath(projectEntity.getLocalPath());
        dto.setTemplate(projectEntity.getTemplate());
        dto.setCreatedAt(projectEntity.getCreatedAt());
        dto.setUpdatedAt(projectEntity.getUpdatedAt());
        return dto;
    }

    public ProjectResponseDTO createProject(ProjectRegistrationDTO dto) {
        validateGitRepository(dto.getLocalPath()); // Validate git repository
        ProjectAnalysisDTO analysis = projectAnalysisService.analyzeProject(dto.getLocalPath());  // analyze project

        ProjectEntity project = new ProjectEntity();
        project.setTitle(dto.getTitle());
        project.setGitRepoLink(dto.getGitRepoLink());
        project.setLocalPath(dto.getLocalPath());
        project.setTemplate(dto.getTemplate());
        project.setCreatedAt(LocalDateTime.now());
        project.setUpdatedAt(LocalDateTime.now());

        ProjectEntity savedProject = projectRepository.save(project);
        gitHookService.installGitHook(savedProject.getLocalPath());
        generateInitialReadme(savedProject, analysis);

        return convertToDTO(savedProject);
    }

    private void generateInitialReadme(ProjectEntity project, ProjectAnalysisDTO analysis) {
        ReadmeGenerationResultDTO result = readmeAiService.generateReadme(project, analysis);

        ReadmeFileEntity readmeFile = ReadmeFileEntity.builder()
                .project(project)
                .content(result.getContent())
                .commitHash("INITIAL")
                .isAutoGenerated(result.getIsAutoGenerated())
                .changeSummary(result.getChangeSummary())
                .createdAt(LocalDateTime.now())
                .build();
        project.setCurrentReadme(readmeFile);
        readmeFileRepository.save(readmeFile);
    }

    // Validate Git repository path
    private void validateGitRepository(String localPath) {
        Path gitPath = Paths.get(localPath, ".git");
        if (!Files.exists(gitPath) || !Files.isDirectory(gitPath)) {
            throw new IllegalArgumentException("Not a valid Git repository: .git folder not found");
        }
    }

    public void deleteProject(Long projectId) {
        ProjectEntity  project = projectRepository.findById(projectId)
                        .orElseThrow(() -> new RuntimeException("Project not found with Id: "+ projectId));
        projectRepository.delete(project);
    }

    public ProjectEntity getProject(Long projectId) {
        ProjectEntity project = projectRepository.findById(projectId)
                .orElseThrow(() ->new RuntimeException("Project not found with Id: "+ projectId));
        return project;
    }
}
