package research.project.documate.backend.Backend.Service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import research.project.documate.backend.Backend.DTOs.ProjectAnalysisDTO;
import research.project.documate.backend.Backend.DTOs.ReadmeGenerationResult;
import research.project.documate.backend.Backend.Entity.ProjectEntity;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

@Service
@Slf4j
@AllArgsConstructor
public class ReadmeAiService {
    private final GeminiService geminiService;

    public ReadmeGenerationResult generateReadme(ProjectEntity project, ProjectAnalysisDTO analysis) {
        String prompt = createDomainSpecificPrompt(project, analysis);
        String aiResponse = geminiService.generateContent(prompt);
        log.info("Response from AI: {}", aiResponse);
        return processAiResponse(project, aiResponse);
    }

    private ReadmeGenerationResult processAiResponse(ProjectEntity project, String aiResponse) {
        try {
            ObjectMapper mapper = new ObjectMapper();
            JsonNode rootNode = mapper.readTree(aiResponse);
            JsonNode textNode = rootNode.path("candidates")
                    .get(0)
                    .path("content")
                    .path("parts")
                    .get(0)
                    .path("text");

            String jsonContent = textNode.asText()
                    .replaceAll("```json\\n?", "")
                    .replaceAll("\\n?```", "")
                    .trim();

            JsonNode readmeJson = mapper.readTree(jsonContent);

            String readmeContent = readmeJson.path("readme_content").asText();
            String changeSummary = readmeJson.path("change_summary").asText();
            List<String> keyFeatures = extractKeyFeatures(readmeJson.path("key_features"));
            List<String> setupSteps = extractSetupSteps(readmeJson.path("setup_steps"));

            return ReadmeGenerationResult.builder()
                    .projectId(project.getId())
                    .content(readmeContent)
                    .changeSummary(changeSummary)
                    .keyFeatures(keyFeatures)
                    .setupSteps(setupSteps)
                    .isAutoGenerated(true)
                    .build();

        } catch (Exception e) {
            log.error("Error processing AI response", e);
            return createDefaultReadme(project);
        }
    }

    private ReadmeGenerationResult createDefaultReadme(ProjectEntity project) {
        String defaultContent = String.format(
                "# %s\n\n" +
                        "## Description\nA project created with DocuMate.\n\n" +
                        "## Setup\nPlease configure your project setup instructions here.\n\n" +
                        "## Usage\nAdd usage instructions here.",
                project.getTitle()
        );

        return ReadmeGenerationResult.builder()
                .projectId(project.getId())
                .content(defaultContent)
                .changeSummary("Initial project setup")
                .keyFeatures(Arrays.asList("Feature 1", "Feature 2"))
                .setupSteps(Arrays.asList("Step 1: Clone repository", "Step 2: Install dependencies"))
                .isAutoGenerated(true)
                .build();
    }

    private List<String> extractKeyFeatures(JsonNode featuresNode) {
        List<String> features = new ArrayList<>();
        if (featuresNode.isArray()) {
            featuresNode.forEach(feature -> features.add(feature.asText()));
        }
        return features.isEmpty() ?
                Arrays.asList("Key features will be added here") :
                features;
    }

    private List<String> extractSetupSteps(JsonNode stepsNode) {
        List<String> steps = new ArrayList<>();
        if (stepsNode.isArray()) {
            stepsNode.forEach(step -> steps.add(step.asText()));
        }
        return steps.isEmpty() ?
                Arrays.asList("Setup steps will be added here") :
                steps;
    }

    private String createDomainSpecificPrompt(ProjectEntity project, ProjectAnalysisDTO analysis) {
        String domainGroup = project.getTemplate().getDomainGroup();

        String domainSpecificInstructions = getDomainInstructions(domainGroup, analysis);
        String readmeStructure = getDomainReadmeStructure(domainGroup);

        return String.format("""
            %s
            
            Project Details:
            Project Name: %s
            Repository: %s
            Template Domain: %s
            Specific Template: %s
            Project Type: %s
            Architecture: %s
            Main Language: %s
            Build Tool: %s
            Key Files: %s
            Sub-projects: %s
            Dependencies: %s
            File Structure: %s
            
            Create a professional README.md following this structure:
            %s
            
            Ensure the response follows the EXACT JSON format shown above.
            """,
                domainSpecificInstructions,
                project.getTitle(),
                project.getGitRepoLink(),
                domainGroup,
                project.getTemplate().getDisplayName(),
                analysis.getProjectType(),
                analysis.getArchitectureType(),
                analysis.getMainLanguage(),
                analysis.getBuildTool(),
                analysis.getKeyFiles(),
                analysis.getSubProjects(),
                analysis.getDependencies(),
                analysis.getFileStructure(),
                readmeStructure
        );
    }

    private String getDomainInstructions(String domainGroup, ProjectAnalysisDTO analysis) {
        switch (domainGroup) {
            case "AI_DATA":
                return """
                    Analyze this AI/Data project and generate a comprehensive README.md in the following EXACT JSON format:
                    {
                        "readme_content": "Full README.md content in markdown format",
                        "change_summary": "Brief summary of AI models, data pipelines, or ML capabilities",
                        "key_features": [
                            "Feature 1",
                            "Feature 2"
                        ],
                        "setup_steps": [
                            "Step 1 description",
                            "Step 2 description"
                        ]
                    }
                    
                    Focus on: AI models, datasets, training procedures, evaluation metrics, data preprocessing, model deployment.
                    """;

            case "WEB_SOFTWARE":
                return """
                    Analyze this Web/Mobile/Software project and generate a comprehensive README.md in the following EXACT JSON format:
                    {
                        "readme_content": "Full README.md content in markdown format",
                        "change_summary": "Brief summary of application functionality and architecture",
                        "key_features": [
                            "Feature 1",
                            "Feature 2"
                        ],
                        "setup_steps": [
                            "Step 1 description",
                            "Step 2 description"
                        ]
                    }
                    
                    Focus on: User interface, APIs, database design, deployment instructions, development setup.
                    """;

            case "CLOUD_INFRA":
                return """
                    Analyze this Cloud/Infrastructure project and generate a comprehensive README.md in the following EXACT JSON format:
                    {
                        "readme_content": "Full README.md content in markdown format",
                        "change_summary": "Brief summary of infrastructure, deployment, and security features",
                        "key_features": [
                            "Feature 1",
                            "Feature 2"
                        ],
                        "setup_steps": [
                            "Step 1 description",
                            "Step 2 description"
                        ]
                    }
                    
                    Focus on: Infrastructure as code, deployment pipelines, security measures, monitoring, scaling.
                    """;

            case "EMERGING_TECH":
                return """
                    Analyze this Emerging Technology project and generate a comprehensive README.md in the following EXACT JSON format:
                    {
                        "readme_content": "Full README.md content in markdown format",
                        "change_summary": "Brief summary of innovative technology implementation",
                        "key_features": [
                            "Feature 1",
                            "Feature 2"
                        ],
                        "setup_steps": [
                            "Step 1 description",
                            "Step 2 description"
                        ]
                    }
                    
                    Focus on: Blockchain smart contracts, game mechanics, innovative algorithms, unique capabilities.
                    """;

            default:
                return getDomainInstructions("WEB_SOFTWARE", analysis);
        }
    }

    private String getDomainReadmeStructure(String domainGroup) {
        switch (domainGroup) {
            case "AI_DATA":
                return """
                    - Project Title & Badges
                    - Description & Purpose
                    - Features & Capabilities
                    - Installation & Setup
                    - Dataset Information
                    - Model Training
                    - Usage Examples
                    - API Documentation (if any)
                    - Evaluation Metrics
                    - Contributing
                    - License
                    """;

            case "WEB_SOFTWARE":
                return """
                    - Project Title & Badges
                    - Description
                    - Features
                    - Screenshots/Demos
                    - Installation
                    - Configuration
                    - Usage
                    - API Reference
                    - Tests
                    - Deployment
                    - Contributing
                    - License
                    """;

            case "CLOUD_INFRA":
                return """
                    - Project Title & Badges
                    - Description
                    - Architecture Diagram
                    - Features
                    - Prerequisites
                    - Installation & Deployment
                    - Configuration
                    - Security
                    - Monitoring
                    - Troubleshooting
                    - Contributing
                    - License
                    """;

            case "EMERGING_TECH":
                return """
                    - Project Title & Badges
                    - Description
                    - Features
                    - Technology Stack
                    - Installation
                    - Usage
                    - Smart Contracts/Game Rules
                    - Testing
                    - Deployment
                    - Contributing
                    - License
                    """;

            default:
                return getDomainReadmeStructure("WEB_SOFTWARE");
        }
    }
}
